import './globals.css';
import { Toaster } from '@/shared/ui/toaster';
import { QueryProvider } from '@/shared/providers/QueryProvider';

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          {children}
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
